# Generated by Django 4.2.6 on 2023-10-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_auto_20231018_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagebox',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='storagebox',
            name='monthly_price_currency',
        ),
    ]
