# Generated by Django 4.2.6 on 2023-10-18 15:48

from django.db import migrations
from django.db import migrations, models
import djmoney.models.fields

class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebox',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=14, default=0),
        ),
        migrations.AddField(
            model_name='storagebox',
            name='monthly_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], max_length=3, default='EUR'),
        ),
    ]
