# Generated by Django 4.2.6 on 2023-10-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0003_remove_storagebox_monthly_price_and_more'),
        ('market_place', '0004_auto_20231018_1833'),
    ]

    operations = [
    ]
